// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"leapp_daemon/models"
)

// NewCreateAwsIamUserSessionParams creates a new CreateAwsIamUserSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAwsIamUserSessionParams() *CreateAwsIamUserSessionParams {
	return &CreateAwsIamUserSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAwsIamUserSessionParamsWithTimeout creates a new CreateAwsIamUserSessionParams object
// with the ability to set a timeout on a request.
func NewCreateAwsIamUserSessionParamsWithTimeout(timeout time.Duration) *CreateAwsIamUserSessionParams {
	return &CreateAwsIamUserSessionParams{
		timeout: timeout,
	}
}

// NewCreateAwsIamUserSessionParamsWithContext creates a new CreateAwsIamUserSessionParams object
// with the ability to set a context for a request.
func NewCreateAwsIamUserSessionParamsWithContext(ctx context.Context) *CreateAwsIamUserSessionParams {
	return &CreateAwsIamUserSessionParams{
		Context: ctx,
	}
}

// NewCreateAwsIamUserSessionParamsWithHTTPClient creates a new CreateAwsIamUserSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAwsIamUserSessionParamsWithHTTPClient(client *http.Client) *CreateAwsIamUserSessionParams {
	return &CreateAwsIamUserSessionParams{
		HTTPClient: client,
	}
}

/* CreateAwsIamUserSessionParams contains all the parameters to send to the API endpoint
   for the create aws iam user session operation.

   Typically these are written to a http.Request.
*/
type CreateAwsIamUserSessionParams struct {

	/* Body.

	   AWS Iam UserName Session create body
	*/
	Body *models.AwsCreateIamUserSessionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAwsIamUserSessionParams) WithDefaults() *CreateAwsIamUserSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAwsIamUserSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) WithTimeout(timeout time.Duration) *CreateAwsIamUserSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) WithContext(ctx context.Context) *CreateAwsIamUserSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) WithHTTPClient(client *http.Client) *CreateAwsIamUserSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) WithBody(body *models.AwsCreateIamUserSessionRequest) *CreateAwsIamUserSessionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create aws iam user session params
func (o *CreateAwsIamUserSessionParams) SetBody(body *models.AwsCreateIamUserSessionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAwsIamUserSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
