// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"leapp_daemon/models"
)

// CreateAwsIamUserSessionReader is a Reader for the CreateAwsIamUserSession structure.
type CreateAwsIamUserSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAwsIamUserSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAwsIamUserSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateAwsIamUserSessionOK creates a CreateAwsIamUserSessionOK with default headers values
func NewCreateAwsIamUserSessionOK() *CreateAwsIamUserSessionOK {
	return &CreateAwsIamUserSessionOK{}
}

/* CreateAwsIamUserSessionOK describes a response with status code 200, with default header values.

MessageResponse
*/
type CreateAwsIamUserSessionOK struct {
	Payload *models.MessageResponse
}

func (o *CreateAwsIamUserSessionOK) Error() string {
	return fmt.Sprintf("[POST /aws/iam-user-sessions][%d] createAwsIamUserSessionOK  %+v", 200, o.Payload)
}
func (o *CreateAwsIamUserSessionOK) GetPayload() *models.MessageResponse {
	return o.Payload
}

func (o *CreateAwsIamUserSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
