// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAwsIamUserSessionParams creates a new DeleteAwsIamUserSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAwsIamUserSessionParams() *DeleteAwsIamUserSessionParams {
	return &DeleteAwsIamUserSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAwsIamUserSessionParamsWithTimeout creates a new DeleteAwsIamUserSessionParams object
// with the ability to set a timeout on a request.
func NewDeleteAwsIamUserSessionParamsWithTimeout(timeout time.Duration) *DeleteAwsIamUserSessionParams {
	return &DeleteAwsIamUserSessionParams{
		timeout: timeout,
	}
}

// NewDeleteAwsIamUserSessionParamsWithContext creates a new DeleteAwsIamUserSessionParams object
// with the ability to set a context for a request.
func NewDeleteAwsIamUserSessionParamsWithContext(ctx context.Context) *DeleteAwsIamUserSessionParams {
	return &DeleteAwsIamUserSessionParams{
		Context: ctx,
	}
}

// NewDeleteAwsIamUserSessionParamsWithHTTPClient creates a new DeleteAwsIamUserSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAwsIamUserSessionParamsWithHTTPClient(client *http.Client) *DeleteAwsIamUserSessionParams {
	return &DeleteAwsIamUserSessionParams{
		HTTPClient: client,
	}
}

/* DeleteAwsIamUserSessionParams contains all the parameters to send to the API endpoint
   for the delete aws iam user session operation.

   Typically these are written to a http.Request.
*/
type DeleteAwsIamUserSessionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAwsIamUserSessionParams) WithDefaults() *DeleteAwsIamUserSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAwsIamUserSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) WithTimeout(timeout time.Duration) *DeleteAwsIamUserSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) WithContext(ctx context.Context) *DeleteAwsIamUserSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) WithHTTPClient(client *http.Client) *DeleteAwsIamUserSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) WithID(id string) *DeleteAwsIamUserSessionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete aws iam user session params
func (o *DeleteAwsIamUserSessionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAwsIamUserSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
