// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"leapp_daemon/models"
)

// NewEditAwsIamUserSessionParams creates a new EditAwsIamUserSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEditAwsIamUserSessionParams() *EditAwsIamUserSessionParams {
	return &EditAwsIamUserSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEditAwsIamUserSessionParamsWithTimeout creates a new EditAwsIamUserSessionParams object
// with the ability to set a timeout on a request.
func NewEditAwsIamUserSessionParamsWithTimeout(timeout time.Duration) *EditAwsIamUserSessionParams {
	return &EditAwsIamUserSessionParams{
		timeout: timeout,
	}
}

// NewEditAwsIamUserSessionParamsWithContext creates a new EditAwsIamUserSessionParams object
// with the ability to set a context for a request.
func NewEditAwsIamUserSessionParamsWithContext(ctx context.Context) *EditAwsIamUserSessionParams {
	return &EditAwsIamUserSessionParams{
		Context: ctx,
	}
}

// NewEditAwsIamUserSessionParamsWithHTTPClient creates a new EditAwsIamUserSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewEditAwsIamUserSessionParamsWithHTTPClient(client *http.Client) *EditAwsIamUserSessionParams {
	return &EditAwsIamUserSessionParams{
		HTTPClient: client,
	}
}

/* EditAwsIamUserSessionParams contains all the parameters to send to the API endpoint
   for the edit aws iam user session operation.

   Typically these are written to a http.Request.
*/
type EditAwsIamUserSessionParams struct {

	/* Body.

	   AWS Iam UserName Session update uri body
	*/
	Body *models.AwsEditIamUserSessionRequest

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edit aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EditAwsIamUserSessionParams) WithDefaults() *EditAwsIamUserSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edit aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EditAwsIamUserSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) WithTimeout(timeout time.Duration) *EditAwsIamUserSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) WithContext(ctx context.Context) *EditAwsIamUserSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) WithHTTPClient(client *http.Client) *EditAwsIamUserSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) WithBody(body *models.AwsEditIamUserSessionRequest) *EditAwsIamUserSessionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) SetBody(body *models.AwsEditIamUserSessionRequest) {
	o.Body = body
}

// WithID adds the id to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) WithID(id string) *EditAwsIamUserSessionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the edit aws iam user session params
func (o *EditAwsIamUserSessionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EditAwsIamUserSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
