// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAwsIamUserSessionParams creates a new GetAwsIamUserSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAwsIamUserSessionParams() *GetAwsIamUserSessionParams {
	return &GetAwsIamUserSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAwsIamUserSessionParamsWithTimeout creates a new GetAwsIamUserSessionParams object
// with the ability to set a timeout on a request.
func NewGetAwsIamUserSessionParamsWithTimeout(timeout time.Duration) *GetAwsIamUserSessionParams {
	return &GetAwsIamUserSessionParams{
		timeout: timeout,
	}
}

// NewGetAwsIamUserSessionParamsWithContext creates a new GetAwsIamUserSessionParams object
// with the ability to set a context for a request.
func NewGetAwsIamUserSessionParamsWithContext(ctx context.Context) *GetAwsIamUserSessionParams {
	return &GetAwsIamUserSessionParams{
		Context: ctx,
	}
}

// NewGetAwsIamUserSessionParamsWithHTTPClient creates a new GetAwsIamUserSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAwsIamUserSessionParamsWithHTTPClient(client *http.Client) *GetAwsIamUserSessionParams {
	return &GetAwsIamUserSessionParams{
		HTTPClient: client,
	}
}

/* GetAwsIamUserSessionParams contains all the parameters to send to the API endpoint
   for the get aws iam user session operation.

   Typically these are written to a http.Request.
*/
type GetAwsIamUserSessionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAwsIamUserSessionParams) WithDefaults() *GetAwsIamUserSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAwsIamUserSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) WithTimeout(timeout time.Duration) *GetAwsIamUserSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) WithContext(ctx context.Context) *GetAwsIamUserSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) WithHTTPClient(client *http.Client) *GetAwsIamUserSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) WithID(id string) *GetAwsIamUserSessionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get aws iam user session params
func (o *GetAwsIamUserSessionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAwsIamUserSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
