// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"leapp_daemon/models"
)

// GetAwsIamUserSessionReader is a Reader for the GetAwsIamUserSession structure.
type GetAwsIamUserSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAwsIamUserSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAwsIamUserSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAwsIamUserSessionOK creates a GetAwsIamUserSessionOK with default headers values
func NewGetAwsIamUserSessionOK() *GetAwsIamUserSessionOK {
	return &GetAwsIamUserSessionOK{}
}

/* GetAwsIamUserSessionOK describes a response with status code 200, with default header values.

AwsGetIamUserSessionResponse
*/
type GetAwsIamUserSessionOK struct {
	Payload *models.AwsGetIamUserSessionResponse
}

func (o *GetAwsIamUserSessionOK) Error() string {
	return fmt.Sprintf("[GET /aws/iam-user-sessions/{id}][%d] getAwsIamUserSessionOK  %+v", 200, o.Payload)
}
func (o *GetAwsIamUserSessionOK) GetPayload() *models.AwsGetIamUserSessionResponse {
	return o.Payload
}

func (o *GetAwsIamUserSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AwsGetIamUserSessionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
