// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"leapp_daemon/models"
)

// StartAwsIamUserSessionReader is a Reader for the StartAwsIamUserSession structure.
type StartAwsIamUserSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartAwsIamUserSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStartAwsIamUserSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStartAwsIamUserSessionOK creates a StartAwsIamUserSessionOK with default headers values
func NewStartAwsIamUserSessionOK() *StartAwsIamUserSessionOK {
	return &StartAwsIamUserSessionOK{}
}

/* StartAwsIamUserSessionOK describes a response with status code 200, with default header values.

MessageResponse
*/
type StartAwsIamUserSessionOK struct {
	Payload *models.MessageResponse
}

func (o *StartAwsIamUserSessionOK) Error() string {
	return fmt.Sprintf("[POST /aws/iam-user-sessions/{id}/start][%d] startAwsIamUserSessionOK  %+v", 200, o.Payload)
}
func (o *StartAwsIamUserSessionOK) GetPayload() *models.MessageResponse {
	return o.Payload
}

func (o *StartAwsIamUserSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
