// Code generated by go-swagger; DO NOT EDIT.

package aws_iam_user_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartAwsIamUserSessionParams creates a new StartAwsIamUserSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartAwsIamUserSessionParams() *StartAwsIamUserSessionParams {
	return &StartAwsIamUserSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartAwsIamUserSessionParamsWithTimeout creates a new StartAwsIamUserSessionParams object
// with the ability to set a timeout on a request.
func NewStartAwsIamUserSessionParamsWithTimeout(timeout time.Duration) *StartAwsIamUserSessionParams {
	return &StartAwsIamUserSessionParams{
		timeout: timeout,
	}
}

// NewStartAwsIamUserSessionParamsWithContext creates a new StartAwsIamUserSessionParams object
// with the ability to set a context for a request.
func NewStartAwsIamUserSessionParamsWithContext(ctx context.Context) *StartAwsIamUserSessionParams {
	return &StartAwsIamUserSessionParams{
		Context: ctx,
	}
}

// NewStartAwsIamUserSessionParamsWithHTTPClient creates a new StartAwsIamUserSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartAwsIamUserSessionParamsWithHTTPClient(client *http.Client) *StartAwsIamUserSessionParams {
	return &StartAwsIamUserSessionParams{
		HTTPClient: client,
	}
}

/* StartAwsIamUserSessionParams contains all the parameters to send to the API endpoint
   for the start aws iam user session operation.

   Typically these are written to a http.Request.
*/
type StartAwsIamUserSessionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartAwsIamUserSessionParams) WithDefaults() *StartAwsIamUserSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start aws iam user session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartAwsIamUserSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) WithTimeout(timeout time.Duration) *StartAwsIamUserSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) WithContext(ctx context.Context) *StartAwsIamUserSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) WithHTTPClient(client *http.Client) *StartAwsIamUserSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) WithID(id string) *StartAwsIamUserSessionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the start aws iam user session params
func (o *StartAwsIamUserSessionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StartAwsIamUserSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
