// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AwsEditIamRoleChainedSessionRequestDto AwsEditIamRoleChainedSessionRequestDto AwsEditIamRoleChainedSessionRequestDto aws edit iam role chained session request dto
//
// swagger:model AwsEditIamRoleChainedSessionRequestDto
type AwsEditIamRoleChainedSessionRequestDto struct {

	// the name which will be displayed
	AccountName string `json:"accountName,omitempty"`

	// the account number of the aws account related to the role
	AccountNumber string `json:"accountNumber,omitempty"`

	// the parent session id, can be an aws plain or federated session
	// it's generated with an uuid v4
	ParentID string `json:"parentId,omitempty"`

	// the region on which the session will be initialized
	Region string `json:"region,omitempty"`

	// the role name
	RoleName string `json:"roleName,omitempty"`
}

// Validate validates this aws edit iam role chained session request dto
func (m *AwsEditIamRoleChainedSessionRequestDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this aws edit iam role chained session request dto based on context it is used
func (m *AwsEditIamRoleChainedSessionRequestDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsEditIamRoleChainedSessionRequestDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsEditIamRoleChainedSessionRequestDto) UnmarshalBinary(b []byte) error {
	var res AwsEditIamRoleChainedSessionRequestDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
