// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AwsIamUserSession aws iam user session
//
// swagger:model AwsIamUserSession
type AwsIamUserSession struct {

	// access key ID label
	AccessKeyIDLabel string `json:"accessKeyIDLabel,omitempty"`

	// account number
	AccountNumber string `json:"accountNumber,omitempty"`

	// ID
	ID string `json:"id,omitempty"`

	// last stop time
	LastStopTime string `json:"lastStopTime,omitempty"`

	// mfa device
	MfaDevice string `json:"mfaDevice,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// named profile ID
	NamedProfileID string `json:"namedProfileID,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// secret key label
	SecretKeyLabel string `json:"secretKeyLabel,omitempty"`

	// session token expiration
	SessionTokenExpiration string `json:"sessionTokenExpiration,omitempty"`

	// session token label
	SessionTokenLabel string `json:"sessionTokenLabel,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`

	// status
	Status AwsSessionStatus `json:"status,omitempty"`
}

// Validate validates this aws iam user session
func (m *AwsIamUserSession) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsIamUserSession) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// ContextValidate validate this aws iam user session based on the context it is used
func (m *AwsIamUserSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsIamUserSession) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AwsIamUserSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsIamUserSession) UnmarshalBinary(b []byte) error {
	var res AwsIamUserSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
