// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AwsSessionStatus AwsSessionStatus AwsSessionStatus aws session status
//
// swagger:model AwsSessionStatus
type AwsSessionStatus int64

// Validate validates this aws session status
func (m AwsSessionStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this aws session status based on context it is used
func (m AwsSessionStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
