// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GcpOauthURLResponse gcp oauth Url response
//
// swagger:model GcpOauthUrlResponse
type GcpOauthURLResponse struct {

	// data
	Data string `json:"Data,omitempty"`

	// message
	Message string `json:"Message,omitempty"`
}

// Validate validates this gcp oauth Url response
func (m *GcpOauthURLResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gcp oauth Url response based on context it is used
func (m *GcpOauthURLResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GcpOauthURLResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpOauthURLResponse) UnmarshalBinary(b []byte) error {
	var res GcpOauthURLResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
