// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// GcpSessionStatus gcp session status
//
// swagger:model GcpSessionStatus
type GcpSessionStatus int64

// Validate validates this gcp session status
func (m GcpSessionStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gcp session status based on context it is used
func (m GcpSessionStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
