// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GcpGetIamUserAccountOauthSessionResponse gcp get iam user account oauth session response
//
// swagger:model GcpGetIamUserAccountOauthSessionResponse
type GcpGetIamUserAccountOauthSessionResponse struct {

	// data
	Data *GcpIamUserAccountOauthSession `json:"Data,omitempty"`

	// message
	Message string `json:"Message,omitempty"`
}

// Validate validates this gcp get iam user account oauth session response
func (m *GcpGetIamUserAccountOauthSessionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpGetIamUserAccountOauthSessionResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this gcp get iam user account oauth session response based on the context it is used
func (m *GcpGetIamUserAccountOauthSessionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpGetIamUserAccountOauthSessionResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {
		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GcpGetIamUserAccountOauthSessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpGetIamUserAccountOauthSessionResponse) UnmarshalBinary(b []byte) error {
	var res GcpGetIamUserAccountOauthSessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
